### ISSUE TITLE
Add "Made in russia" sign to footer

### ISSUE THREAD

**Issue by vladimirshefer** [vladimirshefer/wishlist#15]
https://www.artlebedev.ru/made-in-russia/mark/

like that
![image](https://user-images.githubusercontent.com/23248545/115255680-2e7ab900-a137-11eb-825f-6f216a6383f0.png)

**Comment by Lidiya-prog** [comment]
another pull request was added

**Comment by Lidiya-prog** [comment]
https://github.com/vladimirshefer/wishlist/actions/runs/837117854
