### ISSUE TITLE
Add progress bar to wish

### ISSUE THREAD

**Issue by vladimirshefer** [vladimirshefer/wishlist#22]
Allow users specify the amount of money which they collected to buy the item

In wish card add Progress Bar to visually show how much money was collected
https://getbootstrap.com/docs/4.0/components/progress/

**Comment by Lidiya-prog** [comment]
https://github.com/vladimirshefer/wishlist/pull/34
https://github.com/vladimirshefer/wishlist/pull/37
https://github.com/vladimirshefer/wishlist/pull/36
