### ISSUE TITLE
Use SVG logo in navbar

### ISSUE THREAD

**Issue by vladimirshefer** [vladimirshefer/wishlist#31]
Currently [PNG logo](https://github.com/vladimirshefer/wishlist/blob/master/src/assets/logo.png) is used in navbar

Need to replace with [SVG logo](https://github.com/vladimirshefer/wishlist/blob/master/src/assets/logo.svg)

![image](https://user-images.githubusercontent.com/23248545/117207333-8898a100-adfc-11eb-9a72-eae62913aa93.png)

**Comment by joshtn** [comment]
Hi i'm new. I want to help with this!
